// <auto-generated />
namespace Lupum_Yolcu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class user_change_prop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_change_prop));
        
        string IMigrationMetadata.Id
        {
            get { return "201904080643501_user_change_prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
